const PRODUCTS_FETCH = 'products/PRODUCTS_FETCH'
const PRODUCTS_FETCH_FAILURE = 'products/PRODUCTS_FETCH_FAILURE'
const PRODUCTS_FETCH_SUCCESS = 'products/PRODUCTS_FETCH_SUCCESS'
const PRODUCTS_RESET = 'products/PRODUCTS_RESET'

export { PRODUCTS_FETCH, PRODUCTS_FETCH_FAILURE, PRODUCTS_FETCH_SUCCESS, PRODUCTS_RESET }
