const AUTHENTICATE_BASIC = 'authenticate/EMAIL'
const AUTHENTICATE_BASIC_SUCCESS = 'authenticate/SUCCESS'
const AUTHENTICATE_BASIC_FAILURE = 'authenticate/FAILURE'
const AUTHENTICATE_LOGOUT = 'authenticate/LOGOUT'
const AUTHENTICATE_RESET = 'authenticate/RESET'
const AUTHENTICATE_SET_TOKEN = 'authenticate/SET_TOKEN'
const AUTHENTICATE_REFRESH_TOKEN = 'authenticate/REFRESH_TOKEN'
const AUTHENTICATE_REFRESH_TOKEN_SUCCESS = 'authenticate/REFRESH_TOKEN_SUCCESS'
const AUTHENTICATE_REFRESH_TOKEN_FAILURE = 'authenticate/REFRESH_TOKEN_FAILURE'

export {
    AUTHENTICATE_BASIC,
    AUTHENTICATE_BASIC_SUCCESS,
    AUTHENTICATE_BASIC_FAILURE,
    AUTHENTICATE_LOGOUT,
    AUTHENTICATE_RESET,
    AUTHENTICATE_SET_TOKEN,
    AUTHENTICATE_REFRESH_TOKEN,
    AUTHENTICATE_REFRESH_TOKEN_SUCCESS,
    AUTHENTICATE_REFRESH_TOKEN_FAILURE,
}
